{% set name = "jax2torch" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jax2torch-{{ version }}.tar.gz
  sha256: aa4b499ecf356ae293324a98b5350188d0418c98d0ae60958b7174455ab0b5bb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pytorch >=1.6
    - jax >=0.2.20

test:
  imports:
    - jax2torch
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lucidrains/jax2torch
  summary: Jax 2 Torch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
